//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuropeanLeagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {

        public int Playerid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Clubid { get; set; }
        public string Position { get; set; }
        public string Picture { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public virtual Club Club { get; set; }
        

    }
}
